version: '3'
volumes:
  data:
services:
  mongodb:
    container_name: mongo-auth
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  redis:
    container_name: redis-auth
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data/redis