spring:
  profiles:
    active:
    - prod

---
token: 123SINGLE56

jwt.secret: mysecret
jwt.expiration: 7200000

spring:
  profiles: prod
  application:
    name: merchant-service
  data:
    mongodb:
      uri: ${MONGODB_URI}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  key: session_user
  expiration: 2
