spring:
  profiles:
    active:
    - prod

api.version: @project.version@

---
token: 123SINGLE56

jwt:
  secret: mysecret
  expiration: 7200000

spring:
  profiles: prod
  application:
    name: merchant-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
