token: 123SINGLE56

jwt:
  secret: mysecret
  expiration: 7200000

spring:
  application:
    name: merchant-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/authorization

redis:
  host: localhost
  port: 6379
  password: