package authorizationservice.domain.entities

data class DeviceDetails(
    var userAgent: String? = null,
    var deviceClass: String? = null,
    var deviceName: String? = null,
    var deviceBrand: String? = null,
    var operatingSystemClass: String? = null,
    var operatingSystemName: String? = null,
    var operatingSystemVersion: String? = null,
    var operatingSystemVersionMajor: String? = null,
    var operatingSystemNameVersion: String? = null,
    var operatingSystemNameVersionMajor: String? = null,
    var operatingSystemVersionBuild: String? = null,
    var layoutEngineClass: String? = null,
    var layoutEngineName: String? = null,
    var layoutEngineVersion: String? = null,
    var layoutEngineVersionMajor: String? = null,
    var layoutEngineNameVersion: String? = null,
    var layoutEngineNameVersionMajor: String? = null,
    var agentClass: String? = null,
    var agentName: String? = null,
    var agentVersion: String? = null,
    var agentVersionMajor: String? = null,
    var agentNameVersion: String? = null,
    var agentNameVersionMajor: String? = null,
)
