# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: pull_request

on: [pull_request]

jobs:
       
    test:
      runs-on: ubuntu-latest
      name: test-pr
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: '1.8'
        - name: run unit tests
          run: mvn test
        - name: test report
          run: mvn -B verify -P coverage --no-transfer-progress
        - uses: codecov/codecov-action@v1
          with:
            file: ./**/target/site/jacoco/jacoco.xml
            name: codecov
    
    build:
      needs: test
      runs-on: ubuntu-latest
      name: build-pr
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: '1.8'
        - name: run build
          run: mvn -B package --file pom.xml -Dmaven.test.skip=true -Dspring.profiles.active=prod
